<a href="https://colab.research.google.com/github/Shikha219/Flow/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('clean_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[  0  29  12   5]
 [  0  27  12   5]
 [  0  29  14   5]
 ...
 [158  28  11   6]
 [158  28  12   5]
 [158  40  13   6]]


### Splitting the dataset into the Training set and Test set

In [6]:
print(y)

[17 15 15 ... 17 16 27]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [8]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 200)

Epoch 1/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4892
Epoch 2/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4918
Epoch 3/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4867
Epoch 4/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4983
Epoch 5/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4951
Epoch 6/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4850
Epoch 7/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4903
Epoch 8/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4827
Epoch 9/200
38/38 [==============================] - 0s 2ms/step - loss: 0.5034
Epoch 10/200
38/38 [==============================] - 0s 2ms/step - loss: 0.4873
Epoch 11/200
38/38 [==============================] - 0s 1ms/step - loss: 0.4884
Epoch 12/200
38/38 [==============================] - 0s 2ms/step - loss: 0.5095
Epoch 13/200
38/38 [=================

### Predicting the results of the Test set

In [15]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[16.17 16.  ]
 [15.05 15.  ]
 [15.11 15.  ]
 [16.13 16.  ]
 [17.02 17.  ]
 [16.09 16.  ]
 [24.01 24.  ]
 [25.   25.  ]
 [13.18 13.  ]
 [19.   19.  ]
 [22.97 23.  ]
 [14.09 14.  ]
 [14.13 14.  ]
 [16.16 16.  ]
 [15.11 15.  ]
 [16.08 16.  ]
 [19.84 20.  ]
 [14.12 14.  ]
 [13.16 13.  ]
 [16.07 16.  ]
 [14.13 14.  ]
 [16.14 16.  ]
 [21.97 22.  ]
 [14.11 14.  ]
 [17.06 17.  ]
 [18.99 19.  ]
 [13.16 13.  ]
 [18.2  18.  ]
 [15.14 15.  ]
 [12.28 12.  ]
 [11.23 11.  ]
 [18.01 18.  ]
 [13.15 13.  ]
 [17.98 18.  ]
 [13.23 13.  ]
 [14.13 14.  ]
 [14.15 14.  ]
 [18.11 18.  ]
 [18.11 18.  ]
 [22.05 22.  ]
 [12.25 12.  ]
 [13.17 13.  ]
 [19.95 20.  ]
 [17.04 17.  ]
 [18.   18.  ]
 [17.11 17.  ]
 [11.19 11.  ]
 [25.98 26.  ]
 [13.21 13.  ]
 [16.08 16.  ]
 [12.22 12.  ]
 [20.05 20.  ]
 [13.12 13.  ]
 [21.97 22.  ]
 [21.04 21.  ]
 [13.23 13.  ]
 [13.15 13.  ]
 [19.09 19.  ]
 [12.33 12.  ]
 [16.14 16.  ]
 [13.12 13.  ]
 [13.23 13.  ]
 [24.86 25.  ]
 [14.24 14.  ]
 [18.1  18.  ]
 [18.07 18.  ]
 [18.1  18

### Evaluating the Model Performance

In [22]:
from sklearn.metrics import r2_score, mean_squared_error
r2_score(y_test, y_pred)

0.997959625223972

In [24]:
import math
math.sqrt(mean_squared_error(y_test, y_pred))

0.1600594856303144